config/routes.rb
Rails.application.routes.draw do
  get "admin/show"
  get "admin", to: "admin#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pieces#index"
  get "/pieces", to: "pieces#index"
  get "/pieces/:titleurl", to: "pieces#show"

  resources :subscribers, only: [:create]
  resource :unsubscribe, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/piece.rb
class Piece < ApplicationRecord
    validates :title, presence: true
    validates :textsource, presence: true

    after_create :notify_subscribers

    def notify_subscribers
        Subscriber.all.each do |subscriber|
          PieceMailer.with(piece: self, subscriber: subscriber).new_piece.deliver_later
        end
    end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    generates_token_for :unsubscribe
    after_create :send_welcome_email

    def send_welcome_email
        PieceMailer.with(subscriber: self).welcome_email.deliver_later
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: Rails.application.credentials.dig(:admin, :password)
  def show
    @pieces = Piece.all
    @subscribers = Subscriber.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #allow_browser versions: :modern
end

app/controllers/pieces_controller.rb
require 'open-uri'
require 'pandoc-ruby' 

class PiecesController < ApplicationController
  def index
    @body_color = "#b6aea2"
    @preview_text = Hash.new
    @recent_preview_text = ""
    @pieces = Piece.all
    mostrecent = Time.at(0)

    @pieces.each do |piece|

      if piece.preview_text == nil
        @preview_text[piece.title] = generate_preview_text(piece)
      else
        @preview_text[piece.title] = piece.preview_text
      end

      timestamp = piece.created_at

      #recent text preview
      if (timestamp > mostrecent)
        @recent = piece
        mostrecent = timestamp

        @recent_preview_text = @preview_text[piece.title]
      end

    end

    respond_to do |format|
      format.html do
        if mobile_device?
          render layout: "mobile", template: "pieces/index_mobile"
        else
          render "index"
        end
      end
    end

  end

  def show
    @body_color = "#f3e8d8"
    @piece = Piece.find_by(titleurl: params[:titleurl])
    # Read the RTF file from the source (local or remote)
    rtf_content = URI.open(@piece.textsource).read

    # Parse the RTF content
    @text = PandocRuby.convert(rtf_content, :from => :rtf, :to => :html)
    @text.gsub!(/<p>\\n<\/p>/, "<br>")
    @text.gsub!(/<p(?![^>]*class=)([^>]*)>([^<]*\*\*\*[^<]*)<\/p>/, '<p id="asterisks-break"\1>\2</p>')
    #@text.gsub!(/(<p[^>]*>)(?![^<]*\*\*\*)([^<]+)/, '\1&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp\2')
    #@preview_text = PandocRuby.convert(rtf_content, :from => :rtf, :to => :plain)
    
    respond_to do |format|
      format.html do
        if mobile_device?
          render layout: "mobile", template: "pieces/show_mobile"
        else
          render "show"
        end
      end
    end

  end

  def generate_preview_text(piece)
    rtf_content = URI.open(piece.textsource).read
    preview_text = PandocRuby.convert(rtf_content, :from => :rtf, :to => :plain)

    charindex = 450
    lastchar = preview_text[charindex]

    while lastchar != ' '
      charindex += 1
      lastchar = preview_text[charindex]
    end

    final_preview_text = preview_text[0, charindex] + "..."
    
    piece.update!(preview_text: final_preview_text)
    return final_preview_text
  end

  def mobile_device?
    request.user_agent =~ /Mobile|webOS/
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  
    def create
      # Attempt to find or create a subscriber based on email
      Subscriber.where(subscriber_params).first_or_create
      flash[:notice] = "Subscribed!"
      redirect_to root_path  # or wherever you want to redirect
    end
  
    private
  
    def subscriber_params
      # Permit only the `email` parameter
      params.require(:subscriber).permit(:email)
    end
  end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController

    before_action :set_subscriber
  
    def show
      @subscriber&.destroy
      redirect_to root_path, notice: "Unsubscribed successfully."
    end
  
    private
  
    def set_subscriber
      @subscriber = Subscriber.find_by_token_for(:unsubscribe, params[:token])
    end
  end
  

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/admin/show.html.erb
<h1>Admin View</h1>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed; /* Makes sure cells are equal width and wrap */
  }

  th, td {
    border: 1px solid #ccc;
    padding: 8px;
    word-wrap: break-word;
    white-space: normal;
    vertical-align: top;
  }

  th {
    background-color: #f4f4f4;
  }
</style>

<h2>Pieces Table</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Form</th>
      <th>Date</th>
      <th>Text Source</th>
      <th>Image Source</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th>Title URL</th>
    </tr>
  </thead>
  <tbody>
    <% @pieces.each do |piece| %>
      <tr>
        <td><%= piece.id %></td>
        <td><%= piece.title %></td>
        <td><%= piece.form %></td>
        <td><%= piece.date %></td>
        <td><%= piece.textsource %></td>
        <td><%= piece.imgsource %></td>
        <td><%= piece.created_at %></td>
        <td><%= piece.updated_at %></td>
        <td><%= piece.titleurl %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Subscribers Table</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Created At</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.id %></td>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.created_at %></td>
        <td><%= subscriber.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rw Writing Corner" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Serif:ital,opsz,wght@0,8..144,100..900;1,8..144,100..900&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: <%= @body_color || 'white' %>;">
    <% flash.each do |name, msg| %>
      <div class="alert-<%= name %>" onclick="this.classList.add('fade-out'); setTimeout(() => this.remove(), 1000);">
        <p><%= msg %></p>
      </div>
    <% end %>
    <div class="nav">
      <div></div>
      <div></div>
      <div class = "logo">
        <p id="top">R.W.</p>
        <div class = "bar"></div>
        <p id="bottom">Writing Corner</p>
      </div>
      <div></div>
      <a href="/pieces" class="homebutton">
        <%= image_tag("homeicon.png", width: 30) %>
      </a>
    </div>
    <%= yield %>
    <div class="footer">
      <p>© <%= Time.current.year %> R.W. Writing Corner. All Rights Reserved.  |  rw.writing.corner@gmail.com</p>
    </div>
  </body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rw Writing Corner" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Serif:ital,opsz,wght@0,8..144,100..900;1,8..144,100..900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "mobile", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
<body style="background-color: <%= @body_color || 'white' %>;">
    <% flash.each do |name, msg| %>
      <div class="alert-<%= name %>" onclick="this.classList.add('fade-out'); setTimeout(() => this.remove(), 1000);">
        <p><%= msg %></p>
      </div>
    <% end %>
    <div class="nav">
      <div></div>
      <div></div>
      <div class = "logo">
        <p id="top">R.W.</p>
        <div class = "bar"></div>
        <p id="bottom">Writing Corner</p>
      </div>
      <div></div>
      <a href="/pieces" class="homebutton">
        <%= image_tag("homeicon.png", width: 30) %>
      </a>
    </div>
    <%= yield %>
    <div class="footer">
      <p>© <%= Time.current.year %> R.W. Writing Corner. All Rights Reserved.</p>
      <p>rw.writing.corner@gmail.com</p>
    </div>
  </body>
</html>

app/views/pieces/_piece-preview.html.erb
<a href="/pieces/<%= piece.titleurl %>" class="piece-preview-box">
    <div style="background-image: url('<%= piece.imgsource %>');" class="piece-preview-img">
    </div>
    <div class="piece-preview-text">
    <div id="wrapper">
      <p id="title"><%= piece.title %></p>
      <p id="date"><%= piece.date %></p>
      <p id="text"><%= preview_text %></p>
    </div>
    </div>
</a>

app/views/pieces/index.html.erb
<div class="latestwrapper">
  <div class="circle">
  </div>
  <h1>Latest Piece</h1>
  <div class="latestbox">
    <div style="background-image: url('<%= @recent.imgsource %>');" class="recent-img">
    </div>
    <div class="recent-text">
      <p id="title"><%= @recent.title %></p>
      <p id="date"><%= @recent.date %></p>
      <p id="text"><%= @recent_preview_text %></p>
      <a href="/pieces/<%= @recent.titleurl %>" id="button">Read</a>
    </div>
  </div>
</div>
<div class="all-pieces-wrapper">
  <h1>All Pieces</h1>
  <h2>Short Stories</h2>
  <div class="short-stories-wrapper">
    <% @pieces.each do |piece| %>
      <%= render "piece-preview", piece: piece, preview_text: @preview_text[piece.title]%>
    <% end %>
  </div>
</div>
<div class="subscribe-wrapper">
  <div class="circle2"></div>
  <div class="subscribe-form">
    <h1>Subscribe</h1>
    <p>Get updates when new stories are posted!</p>
    <%= form_with model: Subscriber.new, url: subscribers_path, method: :post, local: true, data: { turbo: false }  do |form| %>
      <%= form.email_field :email, name: "subscriber[email]", placeholder: "you@example.com", required: true %>
      <%= form.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/pieces/index_mobile.html.erb
<div class="latestwrapper">
  <div class="circle">
  </div>
  <h1>Latest Piece</h1>
  <div class="latestbox">
    <div style="background-image: url('<%= @recent.imgsource %>');" class="recent-img">
    </div>
    <div class="recent-text">
      <p id="title"><%= @recent.title %></p>
      <p id="date"><%= @recent.date %></p>
      <p id="text"><%= truncate(@recent_preview_text, length: 200) %></p>
      <a href="/pieces/<%= @recent.titleurl %>" id="button">Read</a>
    </div>
  </div>
</div>
<div class="all-pieces-wrapper">
  <h1>All Pieces</h1>
  <h2>Short Stories</h2>
  <div class="short-stories-wrapper">
    <% @pieces.each do |piece| %>
      <%= render "piece-preview", piece: piece, preview_text: truncate(@preview_text[piece.title], length: 100)%>
    <% end %>
  </div>
</div>
<div class="subscribe-wrapper">
  <div class="circle2"></div>
  <div class="subscribe-form">
    <h1>Subscribe</h1>
    <p>Get updates when new stories are posted!</p>
    <%= form_with model: [Subscriber.new] do |form| %>
        <%= form.email_field :email, placeholder: "you@example.com", required: true %>
        <%= form.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/pieces/show.html.erb
<h1 class="show-title"><%= @piece.title %></h1>
<div style="background-image: url('<%= @piece.imgsource %>');" class="show-img"></div>

<div class="show-text">
  <%= @text.html_safe %>
</div>

app/views/pieces/show_mobile.html.erb
<div class="show-wrapper">
<h1 class="show-title"><%= @piece.title %></h1>
<div style="background-image: url('<%= @piece.imgsource %>');" class="show-img"></div>

<div class="show-text">
  <%= @text.html_safe %>
</div>
</div>